=head1 README

Those are little projects made using Processing an open source language and IDE to easily create images and animations. Its official site is at L<http://processing.org/>.

I started using Processing in may 2010.

=head1 Index

You will find below some descriptions of my various projects.

=over 4

=item BacASable

Click to generate a growing and fading disk. It is supposed to distract my 5 months old daughter :-D

http://hashar.github.com/Processing/BacASable/

=item dancing_rect

Psychedlic moving boxes.

http://hashar.github.com/Processing/dancing_rect/

=item firsttrack

Bouncing balls. Did that using x86 ASM a looong time ago. Processing makes this way easier :-d

http://hashar.github.com/Processing/firsttrack/

=item tombourne

Not sure what it was meant for :-d  Does not draw anything yet!

http://hashar.github.com/Processing/tombourne/

=back
